/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BidV2Interface extends utils.Interface {
  functions: {
    "ERC721Composable_ValidateFingerprint()": FunctionFragment;
    "ERC721_Interface()": FunctionFragment;
    "ERC721_Received()": FunctionFragment;
    "MAX_BID_DURATION()": FunctionFragment;
    "MIN_BID_DURATION()": FunctionFragment;
    "ONE_MILLION()": FunctionFragment;
    "bidCounterByToken(address,uint256)": FunctionFragment;
    "bidIdByTokenAndBidder(address,uint256,address)": FunctionFragment;
    "bidIndexByBidId(bytes32)": FunctionFragment;
    "cancelBid(address,uint256)": FunctionFragment;
    "domainSeparator()": FunctionFragment;
    "executeMetaTransaction(address,bytes,bytes32,bytes32,uint8)": FunctionFragment;
    "feesCollector()": FunctionFragment;
    "feesCollectorCutPerMillion()": FunctionFragment;
    "getBidByBidder(address,uint256,address)": FunctionFragment;
    "getBidByToken(address,uint256,uint256)": FunctionFragment;
    "getChainId()": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "manaToken()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "placeBid(address,uint256,uint256,uint256)": FunctionFragment;
    "placeBid(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "removeExpiredBids(address[],uint256[],address[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltiesCutPerMillion()": FunctionFragment;
    "royaltiesManager()": FunctionFragment;
    "setFeesCollector(address)": FunctionFragment;
    "setFeesCollectorCutPerMillion(uint256)": FunctionFragment;
    "setRoyaltiesCutPerMillion(uint256)": FunctionFragment;
    "setRoyaltiesManager(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ERC721Composable_ValidateFingerprint"
      | "ERC721_Interface"
      | "ERC721_Received"
      | "MAX_BID_DURATION"
      | "MIN_BID_DURATION"
      | "ONE_MILLION"
      | "bidCounterByToken"
      | "bidIdByTokenAndBidder"
      | "bidIndexByBidId"
      | "cancelBid"
      | "domainSeparator"
      | "executeMetaTransaction"
      | "feesCollector"
      | "feesCollectorCutPerMillion"
      | "getBidByBidder"
      | "getBidByToken"
      | "getChainId"
      | "getNonce"
      | "manaToken"
      | "onERC721Received"
      | "owner"
      | "pause"
      | "paused"
      | "placeBid(address,uint256,uint256,uint256)"
      | "placeBid(address,uint256,uint256,uint256,bytes)"
      | "removeExpiredBids"
      | "renounceOwnership"
      | "royaltiesCutPerMillion"
      | "royaltiesManager"
      | "setFeesCollector"
      | "setFeesCollectorCutPerMillion"
      | "setRoyaltiesCutPerMillion"
      | "setRoyaltiesManager"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ERC721Composable_ValidateFingerprint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721_Interface",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721_Received",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BID_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BID_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_MILLION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bidCounterByToken",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "bidIdByTokenAndBidder",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bidIndexByBidId",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTransaction",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feesCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feesCollectorCutPerMillion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBidByBidder",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidByToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "manaToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBid(address,uint256,uint256,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid(address,uint256,uint256,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExpiredBids",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltiesCutPerMillion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltiesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeesCollector",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeesCollectorCutPerMillion",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltiesCutPerMillion",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltiesManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC721Composable_ValidateFingerprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721_Interface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721_Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BID_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BID_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_MILLION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidCounterByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidIdByTokenAndBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidIndexByBidId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feesCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feesCollectorCutPerMillion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidByBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeBid(address,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeBid(address,uint256,uint256,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExpiredBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltiesCutPerMillion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltiesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeesCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeesCollectorCutPerMillion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltiesCutPerMillion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltiesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "BidAccepted(bytes32,address,uint256,address,address,uint256,uint256)": EventFragment;
    "BidCancelled(bytes32,address,uint256,address)": EventFragment;
    "BidCreated(bytes32,address,uint256,address,uint256,uint256,bytes)": EventFragment;
    "ChangedFeesCollectorCutPerMillion(uint256)": EventFragment;
    "ChangedRoyaltiesCutPerMillion(uint256)": EventFragment;
    "FeesCollectorSet(address,address)": EventFragment;
    "MetaTransactionExecuted(address,address,bytes)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RoyaltiesManagerSet(address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BidAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ChangedFeesCollectorCutPerMillion"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ChangedRoyaltiesCutPerMillion"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesCollectorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetaTransactionExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltiesManagerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface BidAcceptedEventObject {
  _id: string;
  _tokenAddress: string;
  _tokenId: BigNumber;
  _bidder: string;
  _seller: string;
  _price: BigNumber;
  _fee: BigNumber;
}
export type BidAcceptedEvent = TypedEvent<
  [string, string, BigNumber, string, string, BigNumber, BigNumber],
  BidAcceptedEventObject
>;

export type BidAcceptedEventFilter = TypedEventFilter<BidAcceptedEvent>;

export interface BidCancelledEventObject {
  _id: string;
  _tokenAddress: string;
  _tokenId: BigNumber;
  _bidder: string;
}
export type BidCancelledEvent = TypedEvent<
  [string, string, BigNumber, string],
  BidCancelledEventObject
>;

export type BidCancelledEventFilter = TypedEventFilter<BidCancelledEvent>;

export interface BidCreatedEventObject {
  _id: string;
  _tokenAddress: string;
  _tokenId: BigNumber;
  _bidder: string;
  _price: BigNumber;
  _expiresAt: BigNumber;
  _fingerprint: string;
}
export type BidCreatedEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber, BigNumber, string],
  BidCreatedEventObject
>;

export type BidCreatedEventFilter = TypedEventFilter<BidCreatedEvent>;

export interface ChangedFeesCollectorCutPerMillionEventObject {
  _feesCollectorCutPerMillion: BigNumber;
}
export type ChangedFeesCollectorCutPerMillionEvent = TypedEvent<
  [BigNumber],
  ChangedFeesCollectorCutPerMillionEventObject
>;

export type ChangedFeesCollectorCutPerMillionEventFilter =
  TypedEventFilter<ChangedFeesCollectorCutPerMillionEvent>;

export interface ChangedRoyaltiesCutPerMillionEventObject {
  _royaltiesCutPerMillion: BigNumber;
}
export type ChangedRoyaltiesCutPerMillionEvent = TypedEvent<
  [BigNumber],
  ChangedRoyaltiesCutPerMillionEventObject
>;

export type ChangedRoyaltiesCutPerMillionEventFilter =
  TypedEventFilter<ChangedRoyaltiesCutPerMillionEvent>;

export interface FeesCollectorSetEventObject {
  _oldFeesCollector: string;
  _newFeesCollector: string;
}
export type FeesCollectorSetEvent = TypedEvent<
  [string, string],
  FeesCollectorSetEventObject
>;

export type FeesCollectorSetEventFilter =
  TypedEventFilter<FeesCollectorSetEvent>;

export interface MetaTransactionExecutedEventObject {
  userAddress: string;
  relayerAddress: string;
  functionSignature: string;
}
export type MetaTransactionExecutedEvent = TypedEvent<
  [string, string, string],
  MetaTransactionExecutedEventObject
>;

export type MetaTransactionExecutedEventFilter =
  TypedEventFilter<MetaTransactionExecutedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RoyaltiesManagerSetEventObject {
  _oldRoyaltiesManager: string;
  _newRoyaltiesManager: string;
}
export type RoyaltiesManagerSetEvent = TypedEvent<
  [string, string],
  RoyaltiesManagerSetEventObject
>;

export type RoyaltiesManagerSetEventFilter =
  TypedEventFilter<RoyaltiesManagerSetEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface BidV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BidV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<[string]>;

    ERC721_Interface(overrides?: CallOverrides): Promise<[string]>;

    ERC721_Received(overrides?: CallOverrides): Promise<[string]>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    ONE_MILLION(overrides?: CallOverrides): Promise<[BigNumber]>;

    bidCounterByToken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    bidIdByTokenAndBidder(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bidIndexByBidId(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cancelBid(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    domainSeparator(overrides?: CallOverrides): Promise<[string]>;

    executeMetaTransaction(
      userAddress: PromiseOrValue<string>,
      functionSignature: PromiseOrValue<BytesLike>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      sigV: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feesCollector(overrides?: CallOverrides): Promise<[string]>;

    feesCollectorCutPerMillion(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBidByBidder(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _bidder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber] & {
        bidIndex: BigNumber;
        bidId: string;
        bidder: string;
        price: BigNumber;
        expiresAt: BigNumber;
      }
    >;

    getBidByToken(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber]>;

    getChainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    getNonce(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nonce: BigNumber }>;

    manaToken(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      _from: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _fingerprint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeExpiredBids(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _bidders: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    royaltiesCutPerMillion(overrides?: CallOverrides): Promise<[BigNumber]>;

    royaltiesManager(overrides?: CallOverrides): Promise<[string]>;

    setFeesCollector(
      _newFeesCollector: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeesCollectorCutPerMillion(
      _feesCollectorCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRoyaltiesCutPerMillion(
      _royaltiesCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRoyaltiesManager(
      _newRoyaltiesManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  ERC721Composable_ValidateFingerprint(
    overrides?: CallOverrides
  ): Promise<string>;

  ERC721_Interface(overrides?: CallOverrides): Promise<string>;

  ERC721_Received(overrides?: CallOverrides): Promise<string>;

  MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

  bidCounterByToken(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bidIdByTokenAndBidder(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  bidIndexByBidId(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelBid(
    _tokenAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  domainSeparator(overrides?: CallOverrides): Promise<string>;

  executeMetaTransaction(
    userAddress: PromiseOrValue<string>,
    functionSignature: PromiseOrValue<BytesLike>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    sigV: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feesCollector(overrides?: CallOverrides): Promise<string>;

  feesCollectorCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

  getBidByBidder(
    _tokenAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _bidder: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, BigNumber] & {
      bidIndex: BigNumber;
      bidId: string;
      bidder: string;
      price: BigNumber;
      expiresAt: BigNumber;
    }
  >;

  getBidByToken(
    _tokenAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, BigNumber]>;

  getChainId(overrides?: CallOverrides): Promise<BigNumber>;

  getNonce(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  manaToken(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    _from: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "placeBid(address,uint256,uint256,uint256)"(
    _tokenAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    _duration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "placeBid(address,uint256,uint256,uint256,bytes)"(
    _tokenAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    _duration: PromiseOrValue<BigNumberish>,
    _fingerprint: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeExpiredBids(
    _tokenAddresses: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _bidders: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  royaltiesCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

  royaltiesManager(overrides?: CallOverrides): Promise<string>;

  setFeesCollector(
    _newFeesCollector: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeesCollectorCutPerMillion(
    _feesCollectorCutPerMillion: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRoyaltiesCutPerMillion(
    _royaltiesCutPerMillion: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRoyaltiesManager(
    _newRoyaltiesManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<string>;

    ERC721_Interface(overrides?: CallOverrides): Promise<string>;

    ERC721_Received(overrides?: CallOverrides): Promise<string>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

    bidCounterByToken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIdByTokenAndBidder(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    bidIndexByBidId(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBid(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    domainSeparator(overrides?: CallOverrides): Promise<string>;

    executeMetaTransaction(
      userAddress: PromiseOrValue<string>,
      functionSignature: PromiseOrValue<BytesLike>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      sigV: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    feesCollector(overrides?: CallOverrides): Promise<string>;

    feesCollectorCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

    getBidByBidder(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _bidder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber] & {
        bidIndex: BigNumber;
        bidId: string;
        bidder: string;
        price: BigNumber;
        expiresAt: BigNumber;
      }
    >;

    getBidByToken(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber]>;

    getChainId(overrides?: CallOverrides): Promise<BigNumber>;

    getNonce(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manaToken(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      _from: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _fingerprint: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeExpiredBids(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _bidders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltiesCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

    royaltiesManager(overrides?: CallOverrides): Promise<string>;

    setFeesCollector(
      _newFeesCollector: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeesCollectorCutPerMillion(
      _feesCollectorCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoyaltiesCutPerMillion(
      _royaltiesCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoyaltiesManager(
      _newRoyaltiesManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BidAccepted(bytes32,address,uint256,address,address,uint256,uint256)"(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: null,
      _seller?: PromiseOrValue<string> | null,
      _price?: null,
      _fee?: null
    ): BidAcceptedEventFilter;
    BidAccepted(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: null,
      _seller?: PromiseOrValue<string> | null,
      _price?: null,
      _fee?: null
    ): BidAcceptedEventFilter;

    "BidCancelled(bytes32,address,uint256,address)"(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: PromiseOrValue<string> | null
    ): BidCancelledEventFilter;
    BidCancelled(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: PromiseOrValue<string> | null
    ): BidCancelledEventFilter;

    "BidCreated(bytes32,address,uint256,address,uint256,uint256,bytes)"(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: PromiseOrValue<string> | null,
      _price?: null,
      _expiresAt?: null,
      _fingerprint?: null
    ): BidCreatedEventFilter;
    BidCreated(
      _id?: null,
      _tokenAddress?: PromiseOrValue<string> | null,
      _tokenId?: PromiseOrValue<BigNumberish> | null,
      _bidder?: PromiseOrValue<string> | null,
      _price?: null,
      _expiresAt?: null,
      _fingerprint?: null
    ): BidCreatedEventFilter;

    "ChangedFeesCollectorCutPerMillion(uint256)"(
      _feesCollectorCutPerMillion?: null
    ): ChangedFeesCollectorCutPerMillionEventFilter;
    ChangedFeesCollectorCutPerMillion(
      _feesCollectorCutPerMillion?: null
    ): ChangedFeesCollectorCutPerMillionEventFilter;

    "ChangedRoyaltiesCutPerMillion(uint256)"(
      _royaltiesCutPerMillion?: null
    ): ChangedRoyaltiesCutPerMillionEventFilter;
    ChangedRoyaltiesCutPerMillion(
      _royaltiesCutPerMillion?: null
    ): ChangedRoyaltiesCutPerMillionEventFilter;

    "FeesCollectorSet(address,address)"(
      _oldFeesCollector?: PromiseOrValue<string> | null,
      _newFeesCollector?: PromiseOrValue<string> | null
    ): FeesCollectorSetEventFilter;
    FeesCollectorSet(
      _oldFeesCollector?: PromiseOrValue<string> | null,
      _newFeesCollector?: PromiseOrValue<string> | null
    ): FeesCollectorSetEventFilter;

    "MetaTransactionExecuted(address,address,bytes)"(
      userAddress?: null,
      relayerAddress?: null,
      functionSignature?: null
    ): MetaTransactionExecutedEventFilter;
    MetaTransactionExecuted(
      userAddress?: null,
      relayerAddress?: null,
      functionSignature?: null
    ): MetaTransactionExecutedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RoyaltiesManagerSet(address,address)"(
      _oldRoyaltiesManager?: PromiseOrValue<string> | null,
      _newRoyaltiesManager?: PromiseOrValue<string> | null
    ): RoyaltiesManagerSetEventFilter;
    RoyaltiesManagerSet(
      _oldRoyaltiesManager?: PromiseOrValue<string> | null,
      _newRoyaltiesManager?: PromiseOrValue<string> | null
    ): RoyaltiesManagerSetEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC721_Interface(overrides?: CallOverrides): Promise<BigNumber>;

    ERC721_Received(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

    bidCounterByToken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIdByTokenAndBidder(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIndexByBidId(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBid(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    domainSeparator(overrides?: CallOverrides): Promise<BigNumber>;

    executeMetaTransaction(
      userAddress: PromiseOrValue<string>,
      functionSignature: PromiseOrValue<BytesLike>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      sigV: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feesCollector(overrides?: CallOverrides): Promise<BigNumber>;

    feesCollectorCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

    getBidByBidder(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _bidder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidByToken(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainId(overrides?: CallOverrides): Promise<BigNumber>;

    getNonce(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manaToken(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      _from: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _fingerprint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeExpiredBids(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _bidders: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    royaltiesCutPerMillion(overrides?: CallOverrides): Promise<BigNumber>;

    royaltiesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setFeesCollector(
      _newFeesCollector: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeesCollectorCutPerMillion(
      _feesCollectorCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRoyaltiesCutPerMillion(
      _royaltiesCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRoyaltiesManager(
      _newRoyaltiesManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC721_Interface(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC721_Received(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ONE_MILLION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bidCounterByToken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bidIdByTokenAndBidder(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bidIndexByBidId(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelBid(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    domainSeparator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeMetaTransaction(
      userAddress: PromiseOrValue<string>,
      functionSignature: PromiseOrValue<BytesLike>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      sigV: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feesCollector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feesCollectorCutPerMillion(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBidByBidder(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _bidder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBidByToken(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNonce(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manaToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      _from: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _duration: PromiseOrValue<BigNumberish>,
      _fingerprint: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeExpiredBids(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _bidders: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    royaltiesCutPerMillion(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    royaltiesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFeesCollector(
      _newFeesCollector: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeesCollectorCutPerMillion(
      _feesCollectorCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRoyaltiesCutPerMillion(
      _royaltiesCutPerMillion: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRoyaltiesManager(
      _newRoyaltiesManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
