name: Deploy
on:
  release:
    types:
      - created
  pull_request:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 24
      - name: install
        run:  npm ci
      - name: build & test & publish
        run:  npm run build
      - name: Publish
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          provenance: false
        env:
